GET http://localhost:3030/users

###
POST http://localhost:3030/users
Content-Type: application/json

{
    "username": "Drbobby",
    "email": "Drbobby@gmail.com",
    "active": true
}

###
DELETE http://localhost:3030/users/51a0ed98-4771-4655-a829-57583b14c826
Content-Type: application/json

